CREATE TABLE IF NOT EXISTS SOURCE (
   ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(50) NOT NULL,
   DRIVER VARCHAR(500) NOT NULL,
   USER VARCHAR(50) NOT NULL,
   PASSWORD VARCHAR(150) NOT NULL,
   URL VARCHAR(500) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS SOURCE_ID_SEQ  MINVALUE 1  MAXVALUE 9999999999999999  START WITH 1  INCREMENT BY 100  CACHE 100;

CREATE TABLE IF NOT EXISTS QUERY (
   ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(50) NOT NULL,
   SQL VARCHAR(5000) NOT NULL,
   SOURCE_ID INT NOT NULL,
   MULTISERIES boolean DEFAULT false,
   PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS QUERY_ID_SEQ  MINVALUE 1  MAXVALUE 9999999999999999  START WITH 1  INCREMENT BY 100  CACHE 100;


CREATE TABLE IF NOT EXISTS PARAMETER (
   ID INT NOT NULL AUTO_INCREMENT,
   QUERY_ID INT NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   DEFAULT_VALUE VARCHAR(5000) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS PARAMETERS_ID_SEQ  MINVALUE 1  MAXVALUE 9999999999999999  START WITH 1  INCREMENT BY 100  CACHE 100;